const AUTH_LOCAL_STORAGE_KEY = 'access_token'
const INFO_USER_LOCAL_STORAGE_KEY = 'info_user'
const TOKEN_FORGOT_PASS = 'token_forgot_pass'

export {AUTH_LOCAL_STORAGE_KEY, INFO_USER_LOCAL_STORAGE_KEY, TOKEN_FORGOT_PASS}
